// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: bundle.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootKey       []byte                 `protobuf:"bytes,1,opt,name=root_key,json=rootKey,proto3" json:"root_key,omitempty"`
	Descriptors   map[string][]byte      `protobuf:"bytes,2,rep,name=descriptors,proto3" json:"descriptors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Pbkdf2Params  *PBKDF2Params          `protobuf:"bytes,3,opt,name=pbkdf2_params,json=pbkdf2Params,proto3" json:"pbkdf2_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyBundle) Reset() {
	*x = KeyBundle{}
	mi := &file_bundle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyBundle) ProtoMessage() {}

func (x *KeyBundle) ProtoReflect() protoreflect.Message {
	mi := &file_bundle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyBundle.ProtoReflect.Descriptor instead.
func (*KeyBundle) Descriptor() ([]byte, []int) {
	return file_bundle_proto_rawDescGZIP(), []int{0}
}

func (x *KeyBundle) GetRootKey() []byte {
	if x != nil {
		return x.RootKey
	}
	return nil
}

func (x *KeyBundle) GetDescriptors() map[string][]byte {
	if x != nil {
		return x.Descriptors
	}
	return nil
}

func (x *KeyBundle) GetPbkdf2Params() *PBKDF2Params {
	if x != nil {
		return x.Pbkdf2Params
	}
	return nil
}

type PBKDF2Params struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Iterations    int32                  `protobuf:"varint,2,opt,name=iterations,proto3" json:"iterations,omitempty"`
	Salt          []byte                 `protobuf:"bytes,3,opt,name=salt,proto3" json:"salt,omitempty"`
	KeyLength     int32                  `protobuf:"varint,4,opt,name=key_length,json=keyLength,proto3" json:"key_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBKDF2Params) Reset() {
	*x = PBKDF2Params{}
	mi := &file_bundle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBKDF2Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBKDF2Params) ProtoMessage() {}

func (x *PBKDF2Params) ProtoReflect() protoreflect.Message {
	mi := &file_bundle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBKDF2Params.ProtoReflect.Descriptor instead.
func (*PBKDF2Params) Descriptor() ([]byte, []int) {
	return file_bundle_proto_rawDescGZIP(), []int{1}
}

func (x *PBKDF2Params) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *PBKDF2Params) GetIterations() int32 {
	if x != nil {
		return x.Iterations
	}
	return 0
}

func (x *PBKDF2Params) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *PBKDF2Params) GetKeyLength() int32 {
	if x != nil {
		return x.KeyLength
	}
	return 0
}

var File_bundle_proto protoreflect.FileDescriptor

const file_bundle_proto_rawDesc = "" +
	"\n" +
	"\fbundle.proto\x12\x15kryptograf.keymgmt.pb\"\x85\x02\n" +
	"\tKeyBundle\x12\x19\n" +
	"\broot_key\x18\x01 \x01(\fR\arootKey\x12S\n" +
	"\vdescriptors\x18\x02 \x03(\v21.kryptograf.keymgmt.pb.KeyBundle.DescriptorsEntryR\vdescriptors\x12H\n" +
	"\rpbkdf2_params\x18\x03 \x01(\v2#.kryptograf.keymgmt.pb.PBKDF2ParamsR\fpbkdf2Params\x1a>\n" +
	"\x10DescriptorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"u\n" +
	"\fPBKDF2Params\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1e\n" +
	"\n" +
	"iterations\x18\x02 \x01(\x05R\n" +
	"iterations\x12\x12\n" +
	"\x04salt\x18\x03 \x01(\fR\x04salt\x12\x1d\n" +
	"\n" +
	"key_length\x18\x04 \x01(\x05R\tkeyLengthB#Z!pkt.systems/kryptograf/keymgmt/pbb\x06proto3"

var (
	file_bundle_proto_rawDescOnce sync.Once
	file_bundle_proto_rawDescData []byte
)

func file_bundle_proto_rawDescGZIP() []byte {
	file_bundle_proto_rawDescOnce.Do(func() {
		file_bundle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bundle_proto_rawDesc), len(file_bundle_proto_rawDesc)))
	})
	return file_bundle_proto_rawDescData
}

var file_bundle_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bundle_proto_goTypes = []any{
	(*KeyBundle)(nil),    // 0: kryptograf.keymgmt.pb.KeyBundle
	(*PBKDF2Params)(nil), // 1: kryptograf.keymgmt.pb.PBKDF2Params
	nil,                  // 2: kryptograf.keymgmt.pb.KeyBundle.DescriptorsEntry
}
var file_bundle_proto_depIdxs = []int32{
	2, // 0: kryptograf.keymgmt.pb.KeyBundle.descriptors:type_name -> kryptograf.keymgmt.pb.KeyBundle.DescriptorsEntry
	1, // 1: kryptograf.keymgmt.pb.KeyBundle.pbkdf2_params:type_name -> kryptograf.keymgmt.pb.PBKDF2Params
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bundle_proto_init() }
func file_bundle_proto_init() {
	if File_bundle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bundle_proto_rawDesc), len(file_bundle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bundle_proto_goTypes,
		DependencyIndexes: file_bundle_proto_depIdxs,
		MessageInfos:      file_bundle_proto_msgTypes,
	}.Build()
	File_bundle_proto = out.File
	file_bundle_proto_goTypes = nil
	file_bundle_proto_depIdxs = nil
}
